name: Fantasy Football Stats Update

on:
  schedule:
    # Run every Monday at 9 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run fantasy football stats script
      env:
        YAHOO_TOKEN: ${{ secrets.YAHOO_TOKEN }}
      run: |
        python getYahooStats.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git diff --staged --quiet || git commit -m "Update fantasy football stats [skip ci]"
        git push
